import type { CoreContext } from '../context'
import type { CoreMessage } from '../index'

import { useLogger } from '@unbird/logg'

import { recordMessages } from '../models/chat-message'

export interface ImportEventToCore {
  'import:data': (data: { 
    data: TelegramExportData
    chatId?: string 
  }) => void
}

export interface ImportEventFromCore {
  'import:progress': (data: { 
    current: number
    total: number
    status: string 
  }) => void
  'import:complete': (data: { 
    imported: number
    errors: number 
  }) => void
  'import:error': (data: { error: unknown }) => void
}

export type ImportEvent = ImportEventFromCore & ImportEventToCore

interface TelegramMessage {
  id: number
  date: string
  from?: string
  from_id?: string | number
  text?: string | Array<{ type: string, text: string }>
  media_type?: string
  file?: string
  photo?: string
}

interface TelegramExportData {
  name: string
  type: string
  id: number
  messages: TelegramMessage[]
}

function convertTelegramMessageToCoreMessage(
  msg: TelegramMessage, 
  chatId: string
): CoreMessage | null {
  // Skip messages without content
  if (!msg.text || (typeof msg.text === 'string' && msg.text.trim() === '')) {
    return null
  }

  // Extract text content
  let content: string
  if (typeof msg.text === 'string') {
    content = msg.text
  } else if (Array.isArray(msg.text)) {
    content = msg.text.map(t => t.text || '').join('')
  } else {
    return null
  }

  // Clean up content
  content = content.trim()
  if (content === '') {
    return null
  }

  // Parse date
  const timestamp = new Date(msg.date).getTime()
  if (isNaN(timestamp)) {
    return null
  }

  // Extract user information
  const fromUserId = msg.from_id ? String(msg.from_id) : (msg.from || 'unknown')
  const fromUserName = msg.from || 'Unknown User'

  return {
    uuid: '', // Will be generated by database
    platformMessageId: String(msg.id),
    chatId,
    content,
    platformTimestamp: timestamp,
    fromId: fromUserId,
    fromName: fromUserName,
    platform: 'telegram',
    reply: {
      isReply: false,
      replyToId: undefined,
      replyToName: undefined,
    },
    forward: {
      isForward: false,
      forwardFromChatId: undefined,
      forwardFromChatName: undefined,
      forwardFromMessageId: undefined,
    },
    vectors: {
      vector1536: undefined,
      vector1024: undefined,
      vector768: undefined,
    },
    jiebaTokens: [],
    media: [],
  }
}

export function registerImportEventHandlers(ctx: CoreContext) {
  const { emitter } = ctx
  const logger = useLogger('core:import:event')

  emitter.on('import:data', async ({ data, chatId }) => {
    try {
      logger.withFields({ 
        chatName: data.name, 
        messageCount: data.messages.length 
      }).log('Starting data import')

      const actualChatId = chatId || String(data.id)
      
      const messages = data.messages
      const total = messages.length
      let imported = 0
      let errors = 0

      emitter.emit('import:progress', { 
        current: 0, 
        total, 
        status: '准备导入数据...' 
      })

      // Process messages in batches
      const batchSize = 100
      for (let i = 0; i < messages.length; i += batchSize) {
        const batch = messages.slice(i, i + batchSize)
        
        try {
          // Convert Telegram export format to CoreMessage format
          const coreMessages: CoreMessage[] = batch
            .map(msg => convertTelegramMessageToCoreMessage(msg, actualChatId))
            .filter((msg): msg is CoreMessage => msg !== null)

          if (coreMessages.length > 0) {
            // Import to database using the recordMessages function
            try {
              const result = await recordMessages(coreMessages)
              result?.expect('Failed to record messages')
              imported += coreMessages.length
            } catch (error) {
              logger.withError(error).error('Failed to import batch')
              errors += batch.length
            }
          }
          
          emitter.emit('import:progress', { 
            current: imported, 
            total, 
            status: `已导入 ${imported} / ${total} 条消息` 
          })
          
        } catch (error) {
          logger.withError(error).error('Failed to import batch')
          errors += batch.length
        }
      }

      emitter.emit('import:complete', { imported, errors })
      logger.withFields({ imported, errors }).log('Import completed')

    } catch (error) {
      logger.withError(error).error('Import failed')
      emitter.emit('import:error', { error })
    }
  })
}