#!/usr/bin/env tsx

import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import process from 'node:process'

import { useLogger } from '@unbird/logg'

import { getDatabaseDSN, initConfig, useConfig } from '../packages/common/src/node'
import { initDrizzle } from '../packages/core/src/db'
import { recordMessages } from '../packages/core/src/models/chat-message'
import type { CoreMessage } from '../packages/core/src/index'

interface TelegramMessage {
  id: number
  date: string
  from?: string
  from_id?: string | number
  text?: string | Array<{ type: string, text: string }>
  media_type?: string
  file?: string
  photo?: string
  reply_to_message_id?: number
  reply_to_text?: string
}

interface TelegramExportData {
  name: string
  type: string
  id: number | string
  messages: TelegramMessage[]
}

async function parseJsonFile(filePath: string): Promise<TelegramExportData> {
  const logger = useLogger('import:parse')
  
  if (!existsSync(filePath)) {
    throw new Error(`文件不存在: ${filePath}`)
  }

  logger.log(`正在解析文件: ${filePath}`)
  
  const fileContent = await readFile(filePath, 'utf-8')
  
  try {
    const data = JSON.parse(fileContent) as TelegramExportData
    
    if (!data.messages || !Array.isArray(data.messages)) {
      throw new Error('无效的 Telegram 导出格式：缺少 messages 数组')
    }
    
    logger.log(`解析成功，找到 ${data.messages.length} 条消息`)
    
    return data
  } catch (error) {
    throw new Error(`JSON 解析失败: ${error instanceof Error ? error.message : String(error)}`)
  }
}

function convertTelegramMessageToCoreMessage(
  msg: TelegramMessage, 
  chatId: string
): CoreMessage | null {
  // Skip messages without content
  if (!msg.text || (typeof msg.text === 'string' && msg.text.trim() === '')) {
    return null
  }

  // Extract text content
  let content: string
  if (typeof msg.text === 'string') {
    content = msg.text
  } else if (Array.isArray(msg.text)) {
    content = msg.text.map(t => t.text || '').join('')
  } else {
    return null
  }

  // Clean up content
  content = content.trim()
  if (content === '') {
    return null
  }

  // Parse date
  const timestamp = new Date(msg.date).getTime()
  if (isNaN(timestamp)) {
    return null
  }

  // Extract user information
  const fromUserId = msg.from_id ? String(msg.from_id) : (msg.from || 'unknown')
  const fromUserName = msg.from || 'Unknown User'

  // Handle reply information
  const isReply = Boolean(msg.reply_to_message_id)
  const replyToId = msg.reply_to_message_id ? String(msg.reply_to_message_id) : ''
  const replyToText = msg.reply_to_text || ''

  return {
    uuid: '', // Will be generated by database
    platformMessageId: String(msg.id),
    chatId,
    content,
    platformTimestamp: timestamp,
    fromId: fromUserId,
    fromName: fromUserName,
    platform: 'telegram',
    reply: {
      isReply: Boolean(msg.reply_to_message_id),
      replyToId: msg.reply_to_message_id ? String(msg.reply_to_message_id) : undefined,
      replyToName: msg.reply_to_text || undefined,
    },
    forward: {
      isForward: false,
      forwardFromChatId: undefined,
      forwardFromChatName: undefined,
      forwardFromMessageId: undefined,
    },
    vectors: {
      vector1536: undefined,
      vector1024: undefined,
      vector768: undefined,
    },
    jiebaTokens: [],
    media: [], // Media processing can be added later if needed
  }
}

async function importMessages(
  data: TelegramExportData,
  chatId?: string
): Promise<{ imported: number, errors: number }> {
  const logger = useLogger('import:messages')
  
  const actualChatId = chatId || String(data.id)
  const chatName = data.name || 'Imported Chat'
  
  logger.log(`开始导入聊天记录: ${chatName} (ID: ${actualChatId})`)
  
  const messages = data.messages
  const total = messages.length
  let imported = 0
  let errors = 0
  
  // Process messages in batches
  const batchSize = 100
  
  for (let i = 0; i < messages.length; i += batchSize) {
    const batch = messages.slice(i, i + batchSize)
    
    try {
      // Convert messages to CoreMessage format
      const coreMessages: CoreMessage[] = batch
        .map(msg => convertTelegramMessageToCoreMessage(msg, actualChatId))
        .filter((msg): msg is CoreMessage => msg !== null)
      
      if (coreMessages.length > 0) {
        // Import to database
        try {
          const result = await recordMessages(coreMessages)
          result?.expect('Failed to record messages')
          imported += coreMessages.length
          logger.log(`批次导入成功: ${coreMessages.length} 条消息 (总进度: ${imported}/${total})`)
        } catch (error) {
          errors += batch.length
          logger.withError(error).error(`批次导入失败: ${batch.length} 条消息`)
        }
      }
      
    } catch (error) {
      logger.withError(error).error(`批次处理失败: ${batch.length} 条消息`)
      errors += batch.length
    }
  }
  
  return { imported, errors }
}

async function main() {
  const logger = useLogger('import:main')
  
  // Parse command line arguments
  const args = process.argv.slice(2)
  
  if (args.length === 0) {
    console.log(`
使用方法: tsx scripts/import-data.ts <JSON文件路径> [聊天ID]

参数:
  <JSON文件路径>  Telegram Desktop 导出的 JSON 文件路径
  [聊天ID]        可选：指定聊天ID，默认使用导出文件中的ID

示例:
  tsx scripts/import-data.ts ./export/ChatExport_001.json
  tsx scripts/import-data.ts ./export/ChatExport_001.json my_custom_chat_id

说明:
  - 支持 Telegram Desktop 导出的 JSON 格式
  - 会自动跳过空消息和无效消息
  - 支持大文件批量导入
  - 重复消息会自动更新而不是创建副本
    `)
    process.exit(1)
  }
  
  const filePath = args[0]
  const customChatId = args[1]
  
  try {
    // Initialize configuration and database
    logger.log('正在初始化配置和数据库连接...')
    await initConfig()
    const config = useConfig()
    
    await initDrizzle(logger, config)
    logger.log('数据库连接已建立')
    
    // Parse the export file
    const data = await parseJsonFile(filePath)
    
    // Import messages
    logger.log('开始导入消息...')
    const startTime = Date.now()
    
    const { imported, errors } = await importMessages(data, customChatId)
    
    const duration = Date.now() - startTime
    
    // Print results
    logger.log('导入完成')
    console.log('\n=== 导入结果 ===')
    console.log(`聊天名称: ${data.name}`)
    console.log(`聊天ID: ${customChatId || data.id}`)
    console.log(`总消息数: ${data.messages.length}`)
    console.log(`成功导入: ${imported}`)
    console.log(`失败/跳过: ${errors}`)
    console.log(`耗时: ${(duration / 1000).toFixed(2)} 秒`)
    
    if (errors > 0) {
      console.log('\n⚠️  部分消息导入失败，请检查日志获取详细信息')
    } else {
      console.log('\n✅ 所有消息导入成功')
    }
    
  } catch (error) {
    logger.withError(error).error('导入失败')
    console.error('\n❌ 导入失败:', error instanceof Error ? error.message : String(error))
    process.exit(1)
  }
}

// Run the script
if (import.meta.url === `file://${process.argv[1]}`) {
  main().catch((error) => {
    console.error('未预期的错误:', error)
    process.exit(1)
  })
}